@startuml

class Jugador {
    - Vida vida[]
    - Puntuacion puntos
    - Prisionero rescatados[]
}

class Marco
class Tarma
class Eri
class Fio

class Arma {
    + Disparar()
}

class Pistola
class HeavyMachineGun
class Lanzacohetes
class Escopeta
class Lanzallamas

class Vehiculo {
    - Vida resistencia
    + Conducir()
}

class MetalSlug
class SlugVolador
class SlugTanque

class Enemigo {
    - Vida salud
    + Atacar()
}

class Soldado
class Oficial
class Rebelde
class TanqueEnemigo
class Helicoptero

class JefeFinal
class JefeMisionUno
class JefeMisionDos
class JefeMisionTres
class JefeMisionCuatro

class Prisionero
class Item
class PowerUp
class Municion
class Bomba

class Vida {
    - BarraVida indicador
}

class BarraVida
class Puntuacion
class Bonus
class Mision {
    - Enemigo listaEnemigos[]
    - Item listaItems[]
    - Tiempo limite
}
class Mundo {
    - Mision niveles[]
}
class Tiempo

Marco --|> Jugador
Tarma --|> Jugador
Eri --|> Jugador
Fio --|> Jugador

Pistola --|> Arma
HeavyMachineGun --|> Arma
Lanzacohetes --|> Arma
Escopeta --|> Arma
Lanzallamas --|> Arma

MetalSlug --|> Vehiculo
SlugVolador --|> Vehiculo
SlugTanque --|> Vehiculo

Soldado --|> Enemigo
Oficial --|> Enemigo
Rebelde --|> Enemigo
TanqueEnemigo --|> Enemigo
Helicoptero --|> Enemigo
JefeFinal --|> Enemigo

JefeMisionUno --|> JefeFinal
JefeMisionDos --|> JefeFinal
JefeMisionTres --|> JefeFinal
JefeMisionCuatro --|> JefeFinal

PowerUp --|> Item
Municion --|> Item
Bomba --|> Item

Jugador "1" o-- "*" Arma
Jugador "1" o-- "0..1" Vehiculo
Jugador "1" *-- "0..3" Vida
Jugador "1" *-- "*" Prisionero

Vehiculo "1" *-- "1" Vida
Enemigo "1" *-- "1" Vida

Vida "1" *-- "1" BarraVida
Jugador "1" *-- "1" Puntuacion
Mundo "1" *-- "1..6" Mision
Mision "1" *-- "*" Enemigo
Mision "1" *-- "*" Item
Mision "1" *-- "1" Tiempo

@enduml